# Generated by Django 5.0.6 on 2024-05-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='joined_date',
            field=models.DateField(null=True),
        ),
    ]
